{
  "gm": "> à¶œà·”à¶©à·Š à¶¸à·à¶±à·’à¶¸à·Š à¶¸à¶œà·™ à¶´à·à¶§à·’à¶ºà·! ðŸ˜˜ðŸ’– Hope you have a beautiful day!",
  "gn": "> à¶œà·”à¶©à·Š à¶±à¶ºà·’à¶§à·Š à¶¸à¶œà·™ à¶´à·à¶§à·’à¶ºà·! ðŸŒ™ See sweet dream my friendðŸ¤¤!",
  "mk": "> à¶¸à·œà¶šà·”à¶­à·Š à¶±à· à¶…à¶±à·™. à¶”à¶ºà· à¶¸à·œà¶šà¶¯ à¶šà¶»à¶±à·Šà¶±à·™ðŸ˜ ! ðŸ˜Œ What about you?",
  "hi": "> à·„à¶ºà·’. à¶”à¶ºà·à¶§ à¶šà·œà¶¸à¶¯ à¶‰à¶­à·’à¶±à·Š! ðŸ˜ What's new with you today?",
  "bye": "> à¶¶à·à¶ºà·’ à¶¸à¶œà·™ à¶´à·à¶§à·’à¶ºà·. à¶´à¶»à·’à·ƒà·Šà·ƒà¶¸à·’à¶±à·Š à¶‰à¶±à·Šà¶± à·„à·œà¶¯à·š! ðŸ˜˜",
  "pakaya": "> à¶‹à¶¶à·™ à¶­à·à¶­à·Šà¶­ à·€à·™à¶±à·Šà¶± à¶‡à¶­à·’ à¶’ ðŸ¤£",
  "ponnaya": "> à¶šà¶½à·’à·ƒà¶¸ à¶œà¶½à·€à· à¶¶à¶½à·à¶œà¶±à·’à¶¸à·Š à¶šà·€à·”à¶¯ à¶´à·œà¶±à·Šà¶±à¶ºà· à¶šà·’à¶ºà¶½à· ðŸ¤£",
  "pakaya": "> à¶´à¶šà¶ºà· à¶‹à¶¶à¶½à¶œà·š à·ƒà·“à¶ºà·ðŸ¤£",
  "fuck": "> à¶¸à·Šà¶¸à·Šà¶¸à·Šà¶¸à·Š à¶†à·ƒà¶ºà·’ à·€à¶œà·š ðŸ¤¤",
  "dewmi": ">  QUEEN DEWMINI MD BOT owner > ADHI OFC",
  "alex": "> à¶† à¶…à¶» à¶šà·œà¶± à¶šà¶´à·à¶œà¶­à·Šà¶­à·” à¶‡à¶½à·™à¶šà·ƒà·Š à¶±à·™à¶¯ ðŸ¤£",
  "yasiya": "> à¶† à¶…à¶» à·„à·œà¶» à¶¶à¶©à·” à¶ºà·ƒà·“ à¶¶à¶¶à· à¶±à·™à¶¯ ðŸ¤£",
  "dewmi": "> à¶¯à·™à·€à·Šà¶¸à·’à¶±à·’ à¶¶à·œà¶§à·Š à·€à·™à¶­à¶§ à¶”à¶¶à·€ à·ƒà·à¶¯à¶»à·™à¶±à·Š à¶´à·’à¶½à·’à¶œà¶±à·Šà¶±à·€à·! ðŸ¤¤ Welcome to Qá´œá´‡á´‡É´ á´…á´‡á´¡á´ÉªÉ´Éª á´á´… bot ðŸ˜˜",
  "huththi": "> à¶’à¶š à¶œà·’à·„à·’à¶±à·Š à¶”à¶ºà·à¶œà·™ à¶…à¶¸à·Šà¶¸à¶§ à¶šà·’à¶ºà¶±à·Šà¶± ðŸ™‚",
  "wesi": "> à¶’à¶š à¶œà·’à·„à·’à¶±à·Š à¶”à¶ºà·à¶œà·™ à¶…à¶¸à·Šà¶¸à¶§ à¶šà·’à¶ºà¶±à·Šà¶± ðŸ™‚",
  "balli": "> à¶’à¶š à¶œà·’à·„à·’à¶±à·Š à¶”à¶ºà·à¶œà·™ à¶…à¶¸à·Šà¶¸à¶§ à¶šà·’à¶ºà¶±à·Šà¶± ðŸ™‚",
  "love you": "> à¶¸à·à¶­à·Š à¶†à¶¯à¶»à·™à¶ºà·’ à¶¸à·à¶±à·’à¶š! ðŸ˜˜ðŸ’– You is my mine!",
  "hate you": "> à¶¸à·Šà¶±à·Š à¶­à¶»à·„à¶ºà·’ à·„à·”à¶¸à·Š! ðŸ˜¢ What did I do? Let's talk it out."
}